export const DIAGNOSES = [
  // Cardiologie
  "Infarctus du myocarde",
  "Syndrome coronarien aigu avec sus décalage ST",
  "Syndrome coronarien aigu sans sus décalage ST",
  "Insuffisance cardiaque congestive",
  "Cardiomyopathie restrictive",
  "Syndrome du QT long",
  "Insuffisance cardiaque chronique",
  "Angor instable",
  "Angor stable",
  "Fibrillation auriculaire",
  "Flutter auriculaire",
  "Tachycardie supraventriculaire",
  "Tachycardie ventriculaire",
  "Fibrillation ventriculaire",
  "Bloc auriculo-ventriculaire",
  "Insuffisance cardiaque aiguë",
  "Insuffisance cardiaque chronique",
  "Péricardite aiguë",
  "Tamponnade cardiaque",
  "Endocardite infectieuse",
  "Dissection aortique",
  "Anévrisme de l'aorte abdominale",
  "Embolie pulmonaire",
  "Thrombose veineuse profonde",
  "Hypertension artérielle",
  "Choc cardiogénique",
  "Rétrécissement aortique (RAO)",
  "Insuffisance mitrale (IM)",
  "Prolapsus valvulaire mitral",
  "Myocardite",
  "Cardiomyopathie dilatée",
  "Cardiomyopathie hypertrophique",

  // Neurologie
  "Accident vasculaire cérébral ischémique",
  "Accident vasculaire cérébral hémorragique",
  "Accident ischémique transitoire",
  "Hémorragie sous-arachnoïdienne",
  "Hémorragie méningée",
  "Thrombose veineuse cérébrale",
  "Méningite bactérienne",
  "Méningite virale",
  "Encéphalite",
  "Épilepsie",
  "Abcès cérébral",
  "État de mal épileptique",
  "Migraine",
  "Migraine avec aura",
  "Algie vasculaire de la face",
  "Névralgie du trijumeau",
  "Sclérose en plaques",
  "Syndrome de Guillain-Barré",
  "Myasthénie grave",
  "Maladie de Parkinson",
  "Démence d'Alzheimer",
  "Hématome extradural",
  "Hématome sous-dural",
  "Hypertension intracrânienne",
  "Vertiges positionnels paroxystiques bénins",
  "Névrite vestibulaire",
  "Neuropathie périphérique",
  "Encéphalopathie de Wernicke",

  // Pneumologie
  "Pneumonie communautaire",
  "Pneumonie franche lobaire aigue (Pneumocoque)",
  "Mycoplasma pneumoniae",
  "Chlamydia pneumpniae",
  "Legionella pneumophila",
  "Pneumonie nosocomiale",
  "Pneumocystose",
  "Pneumothorax spontané",
  "Pneumothorax sous tension",
  "Pleurésie",
  "Embolie pulmonaire",
  "Bronchite aiguë",
  "Exacerbation de BPCO",
  "Asthme aigu grave",
  "Crise d'asthme",
  "Bronchopneumopathie chronique obstructive",
  "Bronchiectasies",
  "Cancer bronchopulmonaire",
  "Sarcoïdose pulmonaire",
  "Fibrose pulmonaire idiopathique",
  "Syndrome de détresse respiratoire aiguë",
  "Œdème pulmonaire aigu (OAP)",
  "Épanchement pleural",
  "Tuberculose pulmonaire",
  "Abcès pulmonaire",

  // Gastroentérologie
  "Appendicite aiguë",
  "Péritonite",
  "Occlusion intestinale",
  "Volvulus du sigmoïde",
  "Invagination intestinale",
  "Hernie étranglée",
  "Ulcère gastroduodénal",
  "Perforation d'ulcère",
  "Hémorragie digestive haute",
  "Hémorragie digestive basse",
  "Gastrite aiguë",
  "Gastroentérite aiguë",
  "Maladie de Crohn",
  "Rectocolite hémorragique",
  "Colite ischémique",
  "Diverticulite aiguë",
  "Pancréatite aiguë",
  "Pancréatite chronique",
  "Cholécystite aiguë",
  "Cholangite aiguë",
  "Lithiase biliaire",
  "Cirrhose hépatique",
  "Hépatite virale aiguë",
  "Hépatite alcoolique",
  "Insuffisance hépatique aiguë",
  "Ischémie mésentérique aiguë",
  "Ascite",
  "Syndrome de Budd-Chiari",
  "Cancer colorectal",
  "Cancer du pancréas",
  "Cancer gastrique",
  "Reflux gastro-oesophagien",
  "Syndrome de l'intestin irritable",

  // Infectiologie
  "Sepsis",
  "Choc septique",
  "Bactériémie",
  "Endocardite infectieuse",
  "Méningite bactérienne",
  "Paludisme",
  "Typhoïde",
  "Brucellose",
  "Tuberculose",
  "VIH",
  "Pneumocystose",
  "Toxoplasmose cérébrale",
  "Cryptococcose",
  "Candidose invasive",
  "Grippe",
  "COVID-19",
  "Légionellose",
  "Listériose",
  "Leptospirose",
  "Rickettsiose",
  "Leishmaniose",
  "Dengue",
  "Érysipèle",
  "Cellulite infectieuse",
  "Fasciite nécrosante",
  "Arthrite septique",
  "Pyélonéphrite aiguë",
  "Cystite aiguë",
  "Prostatite aiguë",
  "Infection sexuellement transmissible",
  "Syphilis (Treponema pallidum)",
  "Gonorrhée (Neisseria gonorrhoeae)",
  "Urétrite gonococcique",
  "Chlamydiose (Chlamydia trachomatis)",
  "Herpès génital (Herpes simplex HSV-1/HSV-2)",

  // Néphrologie
  "Insuffisance rénale aiguë Organique",
  "Insuffisance rénale aiguë Obstructive",
  "Insuffisance rénale aiguë Fonctionnelle",
  "Insuffisance rénale chronique",
  "Syndrome néphrotique",
  "Syndrome néphritique",
  "Glomérulonéphrite aiguë",
  "Pyélonéphrite aiguë",
  "Lithiase rénale",
  "Infection Urinaire Basse (UIB)",
  "Colique néphrétique",
  "Polykystose rénale",
  "Nécrose tubulaire aiguë",
  "Syndrome hémolytique et urémique",
  "Hyponatrémie",
  "Hypernatrémie",
  "Hypokaliémie",
  "Hyperkaliémie",
  "Acidose métabolique",
  "Acidose réspiratoire",
  "Alcalose métabolique",
  "Alcalose réspiratoire",

  // Endocrinologie
  "Diabète de type 1",
  "Diabète de type 2",
  "Acidocétose diabétique",
  "Coma hyperosmolaire",
  "Hypoglycémie",
  "Hypothyroïdie",
  "Hyperthyroïdie",
  "Thyroïdite de Hashimoto",
  "Maladie de Basedow",
  "Thyroïdite subaiguë de De Quervain",
  "Crise thyréotoxique",
  "Insuffisance surrénalienne aiguë",
  "Syndrome de Cushing d'origine surrénalienne (ACTH indépendant)",
  "Syndrome de Cushing d'origine pituitaire (ACTH dépendant)",
  "Maladie de Cushing",
  "Phéochromocytome",
  "Hyperaldostéronisme primaire",
  "Hypercalcémie",
  "Hypocalcémie",
  "Hypoparathyroïdie",
  "Hyperparathyroïdie",
  "Acromégalie",
  "Insuffisance antéhypophysaire",

  // Rhumatologie
  "Polyarthrite rhumatoïde",
  "Lupus érythémateux systémique (LES)",
  "Sclérodermie systémique",
  "Syndrome de Sjögren",
  "Polymyosite",
  "Dermatomyosite",
  "Spondylarthrite ankylosante",
  "Arthrite psoriasique",
  "Goutte",
  "Chondrocalcinose",
  "Arthrose",
  "Fibromyalgie",
  "Vascularite",
  "Maladie de Horton (Artérite à cellules géantes)",
  "Périartérite noueuse",
  "Ostéoporose",
  "Ostéomalacie",

  // Hématologie
  "Anémie ferriprive",
  "Anémie hémolytique",
  "Drépanocytose",
  "Thalassémie",
  "Anémie de Biermer",
  "Syndromes myélodysplasiques",
  "Aplasie médullaire",
  "Leucémie aiguë lymphoblastique",
  "Leucémie aiguë myéloblastique",
  "Leucémie lymphoïde chronique",
  "Leucémie myéloïde chronique",
  "Lymphome de Hodgkin",
  "Lymphome non hodgkinien",
  "Myélome multiple",
  "Purpura thrombopénique immunologique",
  "Coagulation intravasculaire disséminée (CIVD)",
  "Hémophilie",
  "Thrombocytémie essentielle",
  "Polyglobulie de Vaquez",

  // Urgences et réanimation
  "Arrêt cardiorespiratoire",
  "Choc anaphylactique",
  "Choc hypovolémique",
  "Choc obstructif",
  "Intoxication au paracétamol",
  "Intoxication aux benzodiazépines",
  "Intoxication aux opioïdes",
  "Intoxication au monoxyde de carbone",
  "Noyade",
  "Brûlures graves",
  "Hypothermie",
  "Coup de chaleur",
  "Traumatisme crânien",
  "Traumatisme thoracique",
  "Traumatisme abdominal",
  "Polytraumatisme",

  // Psychiatrie
  "Dépression majeure",
  "Trouble bipolaire",
  "Schizophrénie",
  "Trouble anxieux généralisé",
  "Attaque de panique",
  "Trouble obsessionnel compulsif",
  "État de stress post-traumatique",
  "Delirium",
  "Syndrome de sevrage alcoolique",
  "Delirium tremens",
  
  // Pédiatrie
 "Bronchiolite aiguë",
 "Asthme de l'enfant",
 "Ictère néonatal",
 "Crise convulsive fébrile",
 "Gastro-entérite aiguë de l'enfant",
 "Purpura rhumatoïde",
 "Maladie de Kawasaki",
 "Crise vaso-occlusive",
 "Sténose hypertrophique du pylore",
 "Déshydratation aiguë",
 "Pneumonie de l'enfant",
 "Otite moyenne aiguë",
 "Coqueluche (Bordetella pertussis)",
 "Rougeole",
 "Rubéole",
 "Ethmoidite aiguë",
 "Laryngite aiguë",
 "Épiglottite aiguë",
 "Roséole infantile",
 "Scarlatine",
 "Oreillons",
 "Méningite bactérienne de l'enfant",
 "Méningite virale de l'enfant",
 "Varicelle",
 "Méningite de l'enfant",
 "Invagination intestinale",

 // Gynécologie - Obstétrique
"Grossesse extra-utérine",
"Menace de fausse couche",
"Fausse couche spontanée",
"Grossesse molaire",
"Hyperémèse gravidique",
"Prééclampsie",
"Éclampsie",
"Syndrome HELLP",
"Hématome rétroplacentaire",
"Placenta prævia",
"Rupture utérine",
"Rupture prématurée des membranes",
"Chorioamniotite",
"Menace d'accouchement prématuré",
"Hémorragie du post-partum",
"Endométrite du post-partum",
"Grossesse ectopique rompue",
"Maladie inflammatoire pelvienne",
"Salpingite aiguë",
"Torsion d'annexe",
"Kyste ovarien rompu",
"Kyste ovarien compliqué",
"Abcès tubo-ovarien",
"Endométriose",
"Fibrome utérin symptomatique",
"Syndrome des ovaires polykystiques",
"Cancer du col de l'utérus",
"Cancer de l'endomètre",
"Cancer de l'ovaire",

// Orthopédie - Traumatologie
"Fracture du col du fémur",
"Fracture de la diaphyse fémorale",
"Fracture du radius distal",
"Fracture de Pouteau-Colles",
"Fracture du scaphoïde",
"Fracture de la clavicule",
"Fracture de l'humérus proximal",
"Fracture supracondylienne de l'humérus",
"Fracture bimalléolaire",
"Fracture du plateau tibial",
"Fracture ouverte",
"Luxation de l'épaule",
"Luxation de la hanche",
"Luxation du coude",
"Entorse de la cheville",
"Rupture du ligament croisé antérieur",
"Rupture du tendon d'Achille",
"Syndrome des loges",
"Syndrome de la queue de cheval",
"Compression médullaire aiguë",
"Ostéomyélite",
"Arthrite septique",
"Spondylodiscite",
"Hernie discale lombaire",
"Lombosciatique",
"Sarcome d'Ewing",
"Ostéosarcome",
"Sciatique",

// Ophtalmologie
"Conjonctivite virale",
"Conjonctivite bactérienne",
"Conjonctivite allergique",
"Kératite infectieuse",
"Ulcère cornéen",
"Abrasion cornéenne",
"Corps étranger cornéen",
"Glaucome aigu par fermeture de l'angle",
"Uvéite antérieure",
"Hémorragie sous-conjonctivale",
"Occlusion de l'artère centrale de la rétine",
"Occlusion de la veine centrale de la rétine",
"Décollement de rétine",
"Névrite optique rétrobulbaire (NORB)",
"Neuropathie optique ischémique antérieure",
"Cellulite orbitaire",
"Cellulite préseptale",
"Endophtalmie",
"Chalazion",
"Orgelet",
"Paralysie du nerf oculomoteur (III)",
"Paralysie du nerf trochléaire (IV)",
"Paralysie du nerf abducens (VI)",
"Rétinopathie diabétique",
"Dégénérescence maculaire liée à l'âge",
"Cataracte",
"kérato-conjonctivite (Trachome)",

// Dermatologie
"Zona",
"Érysipèle",
"Teigne des pieds (pied d'athlète)",
"Teigne du cuir chevelu (à dermatophyte)",
"Cellulite bactérienne",
"Impétigo",
"Érythème polymorphe",
"Syndrome de Stevens-Johnson",
"Nécrolyse épidermique toxique",
"Érythème noueux",
"Psoriasis",
"Eczéma séborrhéique (dermatite séborrhéique)",
"Eczéma nummulaire",
"Dermatite atopique (eczéma atopique)",
"Dermatite de contact (eczéma de contact)",
"Dyshidrose",
"Urticaire aiguë",
]
// Common abbreviations and aliases for diagnoses
export const ABBREVIATIONS: Record<string, string[]> = {
  'HSA': ['Hémorragie sous-arachnoïdienne'],
  'AVC': ['Accident vasculaire cérébral ischémique', 'Accident vasculaire cérébral hémorragique'],
  'IAT': ['Accident ischémique transitoire'],
  'AIT': ['Accident ischémique transitoire'],
  'SCA': ['Syndrome coronarien aigu'],
  'IDM': ['Infarctus du myocarde'],
  'IM': ['Insuffisance mitrale'],
  'RAO': ['Rétrécissement aortique'],
  'BPCO': ['Bronchopneumopathie chronique obstructive'],
  'PFLA':['Pneumonie franche lobaire aigue (Pneumocoque)'],
  'EP': ['Embolie pulmonaire'],
  'TVP': ['Thrombose veineuse profonde'],
  'IRC': ['Insuffisance rénale chronique'],
  'LES': ['Lupus érythémateux systémique'],
  'PR': ['Polyarthrite rhumatoïde'],
  'TB': ['Tuberculose pulmonaire'],
  'VIH': ['VIH'],
  'COVID': ['COVID-19'],
  'FCF': ['Fracture du col du fémur'],
  'GEU': ['Grossesse extra-utérine'],
  'LH': ['Lymphome de Hodgkin'],
  'LNH': ['Lymphome non hodgkinien'],
  'LAL': ['Leucémie aiguë lymphoblastique'],
  'LAM': ['Leucémie aiguë myéloblastique'],
  'LMC':['Leucémie myéloïde chronique'],
  'LLC': ['Leucémie lymphoïde chronique'],
  'STEMI': ['Syndrome coronarien aigu avec sus décalage ST'],
  'NSTEMI': ['Syndrome coronarien aigu sans sus décalage ST'],
  'GAFA': ['galuacome aigue par fermeture de l-angle'],
  'Heat stroke': ['Coup de chaleur'],
  'PTI':['Purpura thrombopénique immunologique'],
  'CIVD': ['Coagulation intravasculaire disséminée'],
  'SMD':['Syndromes myélodysplasiques'],
  'SHP':['Sténose hypertrophique du pylore'],
  'IRA':['Insuffisance rénale aiguë Organique','Insuffisance rénale aiguë Obstructive','Insuffisance rénale aiguë Fonctionnelle'],
}